### ISSUE TITLE
 Android client SDK allows customizing audio input?

### ISSUE THREAD

**Issue by zengxianhua** [open-webrtc-toolkit/owt-client-native#103]
in sdk document i found these description:

1 Implement com.intel.webrtc.base.IcsAudioRecord.AudioFrameGeneratorInterface;

2 Call WebRtcUtils.setCustomizedAudioInput(AudioFrameGeneratorInterface) before instantiating PeerClient or ConferenceClient;

 

however, i can't find these classes in sdk, have these been removed from ? how can I customize audio input?  Any suggestions with native implementation?

**Comment by jianjunz** [comment]
It is removed in the latest version. You may implement a custom ADM to achieve this feature.

**Comment by jianjunz** [comment]
The repository for Android SDK is https://github.com/open-webrtc-toolkit/owt-client-android. This repo is a dependency of Android repo, but it's mainly for iOS and Windows.
