### ISSUE TITLE
Retain-cycle between OWTConferenceClient and its delegate

### ISSUE THREAD

**Issue by qiaoxueshi** [open-webrtc-toolkit/owt-client-native#104]
Say I have an iOS ViewController which retain a `OWTConferenceClient` instance, and set this view controller as its delegate (this delegate-pattern is very common in iOS development),  although OWTConferenceClient's delegate is weak, but it strong reference an `observer_` property which will strong reference to the delegate, so the retain-cycle happened:

"->" means strong reference
My ViewController -> OWTConferenceClient -> observer_ -> delegate( My ViewController).

https://github.com/open-webrtc-toolkit/owt-client-native/blob/608ec4959fdc1ab656d47ed3686bd051bf2c9157/talk/owt/sdk/conference/objc/ConferenceClientObserverObjcImpl.h#L34-L35

https://github.com/open-webrtc-toolkit/owt-client-native/blob/608ec4959fdc1ab656d47ed3686bd051bf2c9157/talk/owt/sdk/conference/objc/OWTConferenceClient.mm#L238-L247

I have tried some ways to break the retain-cycle, such as add "__weak" before the property. 

```
__weak id<OWTConferenceClientDelegate> delegate_; 
```
I simulated a similar problem situation in my Xcode Test project, adding "__weak" works, but it doesn't work in the OWT project, may be I missed some complier flags..  I don't have much experience on C++ nor Objective-C++, so maybe anyone else know how to fix this?

**Comment by qiaoxueshi** [comment]
The same problem exists in OWTConferencePublication/ConferencePublicationObserverObjcImpl and OWTConferenceSubscription/ConferenceSubscriptionObserverObjcImpl .

**Comment by jianjunz** [comment]
Thanks for reporting this issue. You may submit a PR to fix them or we'll fix them later.

**Comment by qiaoxueshi** [comment]
> Thanks for reporting this issue. You may submit a PR to fix them or we'll fix them later.

OK, I have fixed 3 main retain-cycles, I will submit a PR ASAP

**Comment by qiaoxueshi** [comment]
fixed in  PR #108

**Comment by wbtvc** [comment]
> fixed in PR #108

OWTRemoteStreamDelegate
OWTConferenceParticipant
have same bug, if you set that two delegate, the deleagte will never release.
please fix it, thank you.
