### ISSUE TITLE
What is the version of WebRTC used in OWT of iOS ? Can I change to the M70 version?

### ISSUE THREAD

**Issue by zhangyu1992** [open-webrtc-toolkit/owt-client-native#120]
What is the version of WebRTC used in OWT of iOS ? Can I change to the M70 version?
I see

**Comment by jianjunz** [comment]
The latest version of iOS SDK depends on WebRTC M70. But we made some changes to the WebRTC code. You may find the code [here](https://github.com/open-webrtc-toolkit/owt-deps-webrtc).

**Comment by zhangyu1992** [comment]
thank you
