### ISSUE TITLE
gclient sync time out 

### ISSUE THREAD

**Issue by mackobe** [open-webrtc-toolkit/owt-client-native#154]
gclient sync一直(7) Failed to connect to chrome-infra-packages.appspot.com port 443: Operation timed out 换了好几个梯子都是这样，有其他有效解决方案吗？

**Comment by zhouhuirun2015** [comment]
使用阿里云/华为云创建香港/国外的服务器

**Comment by huenchao** [comment]
> gclient sync一直(7) Failed to connect to chrome-infra-packages.appspot.com port 443: Operation timed out 换了好几个梯子都是这样，有其他有效解决方案吗？

怎么解决的呢

**Comment by ppjuns** [comment]
ss开全局，设置环境变量
export http_proxy=http://127.0.0.1:1087
export https_proxy=http://127.0.0.1:1087
