### ISSUE TITLE
windows client create camera stream twice cause crash

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#165]
The thread 0x5794 has exited with code 0 (0x0).
(video_capture_ds.cc:123): Failed to Pause the Capture device. Is it already occupied? -2147023446
The thread 0x54ac has exited with code 0 (0x0).
(vcmcapturer.cc:71): Failed to create VcmCapturer(w = 640, h = 480, fps = 30)
Exception thrown at 0x015C92A9 in OWTConference.exe: 0xC0000005: Access violation reading location 0x00000004.

>	OWTConference.exe!webrtc::VideoTrack::VideoTrack(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & label, webrtc::VideoTrackSourceInterface * video_source, rtc::Thread * worker_thread) Line 29	C++
 	OWTConference.exe!rtc::RefCountedObject<webrtc::VideoTrack>::RefCountedObject<webrtc::VideoTrack><std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,webrtc::VideoTrackSourceInterface * &,rtc::Thread * &>(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & p0, webrtc::VideoTrackSourceInterface * & p1, rtc::Thread * & <args_0>) Line 34	C++
 	OWTConference.exe!webrtc::VideoTrack::Create(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & id, webrtc::VideoTrackSourceInterface * source, rtc::Thread * worker_thread) Line 97	C++
 	OWTConference.exe!webrtc::PeerConnectionFactory::CreateVideoTrack(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & id, webrtc::VideoTrackSourceInterface * source) Line 296	C++
 	OWTConference.exe!webrtc::ReturnType<rtc::scoped_refptr<webrtc::VideoTrackInterface> >::Invoke<webrtc::PeerConnectionFactoryInterface,rtc::scoped_refptr<webrtc::VideoTrackInterface> (__thiscall webrtc::PeerConnectionFactoryInterface::*)(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,webrtc::VideoTrackSourceInterface *),std::basic_string<char,std::char_traits<char>,std::allocator<char> >,webrtc::VideoTrackSourceInterface *>(webrtc::PeerConnectionFactoryInterface * c, rtc::scoped_refptr<webrtc::VideoTrackInterface>(webrtc::PeerConnectionFactoryInterface::*)(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, webrtc::VideoTrackSourceInterface *) m, std::basic_string<char,std::char_traits<char>,std::allocator<char> > a1, webrtc::VideoTrackSourceInterface * a2) Line 85	C++
 	OWTConference.exe!webrtc::MethodCall2<webrtc::PeerConnectionFactoryInterface,rtc::scoped_refptr<webrtc::VideoTrackInterface>,std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,webrtc::VideoTrackSourceInterface *>::OnMessage(rtc::Message * __formal) Line 253	C++
 	OWTConference.exe!webrtc::internal::SynchronousMethodCall::OnMessage(rtc::Message * __formal) Line 33	C++
 	OWTConference.exe!rtc::MessageQueue::Dispatch(rtc::Message * pmsg) Line 514	C++
 	OWTConference.exe!rtc::Thread::ProcessMessages(int cmsLoop) Line 536	C++
 	OWTConference.exe!rtc::Thread::Run() Line 359	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	Unknown

**Comment by taste1981** [comment]
fix by #166
