### ISSUE TITLE
branch 76 crash with publish a local stream

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#171]
(rtc_event_log_impl.cc:63): Creating legacy encoder for RTC event log.
(peer_connection_factory.cc:361): Using default network controller factory
(bitrate_prober.cc:69): Bandwidth probing enabled, set to inactive
(paced_sender.cc:201): bwe:pacer_updated pacing_kbps=300 padding_budget_kbps=0
(paced_sender.cc:421): ProcessThreadAttached 0x36e07c0
(cpu_info.cc:53): Available number of cores: 8
(aimd_rate_control.cc:105): Using aimd rate control with back off factor 0.85
(remote_bitrate_estimator_single_stream.cc:71): RemoteBitrateEstimatorSingleStream: Instantiating.
(remote_estimator_proxy.cc:44): Maximum interval between transport feedback RTCP messages (ms): 250
(webrtc_session_description_factory.cc:178): DTLS-SRTP enabled; sending DTLS identity request (key type: 1).
(openssl_identity.cc:44): Making key pair
(conferencepeerconnectionchannel.cc:390): Publish a local stream.
(openssl_identity.cc:92): Returning key pair
(openssl_certificate.cc:58): Making certificate for WebRTC
(openssl_certificate.cc:108): Returning certificate
(webrtc_session_description_factory.cc:480): Setting new certificate.
(conferencesocketsignalingchannel.cc:760): Received ack for message ID: 2
(conferencesocketsignalingchannel.cc:454): Received ack from server.
(conferencepeerconnectionchannel.cc:889): Setting session ID for current channel
(conferencepeerconnectionchannel.cc:104): Create offer.
Exception thrown: read access violation.
this->configuration_.video._Mypair._Myval2.**_Myfirst** was nullptr.

`>	OWTConference.exe!owt::base::PeerConnectionChannel::OnMessage(rtc::Message * msg) Line 205	C++
 	OWTConference.exe!rtc::MessageQueue::Dispatch(rtc::Message * pmsg) Line 514	C++
 	OWTConference.exe!rtc::Thread::ProcessMessages(int cmsLoop) Line 536	C++
 	OWTConference.exe!rtc::Thread::Run() Line 359	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	Unknown
`

**Comment by taste1981** [comment]
Fix by #173
