### ISSUE TITLE
Android p2p client cannot publish stream to ios or windows client after publish to it.

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#179]
1. ios p2p client login and add allowed  android client
2. android p2p client  login and add allowed ios client
3. ios publish to android client
4. android client publish to ios client

expected : android publish to ios succeed
actual: android client can not publish to ios succeed

**Comment by zhangyihui1** [comment]
4.3 verified

**Comment by zhangyihui1** [comment]
windows also found this issue

**Comment by JinChengShi** [comment]
js also cannot publish to windows client after windows client publish to js.

**Comment by JamesTerm** [comment]
The same is true for running chrome on either a desktop or android to windows client.  I made note of this in issue #122... See if you are getting the "Attempt to perform PeerConnection operation when it is closed" message.  I've made a work around solution that I've included in this issue.   One thing that does work is if the chrome client issues the publish first... then all works fine.  I'm really surprised how this issue has been under the radar for so long.  My guess is that the top-end of the testing expects that the caller always issues the publish first.  

### _I really would like to hear some response to this._
