### ISSUE TITLE
iOS archive problem

### ISSUE THREAD

**Issue by mackobe** [open-webrtc-toolkit/owt-client-native#185]
hi ：
 when i archived, i found this question 
https://github.com/mackobe/KTYSipFramework/blob/master/WX20190910-175854%402x.png
but when i built in my devcie, it was work. I use "libsioclient_tls_no_verification.a" file
Can you tell me how to fix it .
Thanks.

**Comment by mackobe** [comment]
and i found it was not always happen , i dont konw how to resolve it

**Comment by jianjunz** [comment]
The libraries we provide only contains x64, armv7 and arm64. If you try run it on x86 simulator, it may report undefined symbols.

**Comment by mackobe** [comment]
yes  build is ok, but when i try to archive,it happens.
