### ISSUE TITLE
windows conference client publish vp9 codec stream will blurred screen when do trans-code

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#194]

**Comment by taste1981** [comment]
@daijh Please help to check from MCU side.

**Comment by HuaChunbo** [comment]
Run with Chrome 77 with VP9 forwarded from Windows client without trans-coding, which turned out to be good. It seems the decoding of VP9 on MCU needs to be checked.

**Comment by taste1981** [comment]
MCU is answering with vp9 profile-id 2 while client is offering profile-id 0 and 2;

Actually current MCU only supports 8-bit encoding, so it must remove codec of profile-id 2 from the answer SDP. Assigning to Li for further handling.

**Comment by taste1981** [comment]
fixed by owt-server PR #310
