### ISSUE TITLE
how to switch camera between front and back?

### ISSUE THREAD

**Issue by yiyuan-liaoqiang** [open-webrtc-toolkit/owt-client-native#223]
In iOS plateform,how to switch camera between front and back?

**Comment by jianjunz** [comment]
`OWTLocalStream` can be initialized with `RTCMediaStream`. Please create an `RTCMediaStream` in your app, and you're able to control its source.

**Comment by mackobe** [comment]
> In iOS plateform,how to switch camera between front and back?

hi, have you fixed it?
I use "initWithMediaStream", but when i published it to web, it can't attach and have no video and the video frame was {0.0}

**Comment by yiyuan-liaoqiang** [comment]
> > In iOS plateform,how to switch camera between front and back?
> 
> hi, have you fixed it?
> I use "initWithMediaStream", but when i published it to web, it can't attach and have no video and the video frame was {0.0}

yeah
