### ISSUE TITLE
Android build fail

### ISSUE THREAD

**Issue by chenxiemin** [open-webrtc-toolkit/owt-client-native#250]
### Error: 

ERROR at //build/config/android/internal_rules.gni:172:23: Can't load input file.
            deps += [ "$_target_label$build_config_target_suffix" ]

### Step:

**git clone https://github.com/open-webrtc-toolkit/owt-client-native.git src**
**vi .gclient, edit with**

_solutions = [
  {
     "managed": False,
     "name": "src",
     "url": "https://github.com/open-webrtc-toolkit/owt-client-native.git",
     "custom_deps": {},
     "deps_file": "DEPS",
     "safesync_url": "",
  },
]
target_os = [ "android" ]_

**gclient sync**
**cd src**
**python scripts/build_android.py**

**Comment by jzqnjzy** [comment]
root@webrtc:/owt/src/src# python ./scripts/build_android.py 
> args: Namespace(debug=False, output_path='/owt/src/src/out', target_arch='arm,arm64,x86')
> generating args for arm release
ERROR at //build/config/android/internal_rules.gni:172:23: Can't load input file.
            deps += [ "$_target_label$build_config_target_suffix" ]
                      ^------------------------------------------
Unable to load:
  /owt/src/src/modules/audio_device/BUILD.gn
I also checked in the secondary tree for:
  /owt/src/src/build/secondary/modules/audio_device/BUILD.gn

**Comment by chenxiemin** [comment]
Can anybody help on it?

**Comment by yanbin7** [comment]
Do you use master source code ?  please use branch 4.2.x for Android build

**Comment by chenxiemin** [comment]
4.2.x works fine, thanks.
