### ISSUE TITLE
Getting error while trying to build for iOS

### ISSUE THREAD

**Issue by routsrv** [open-webrtc-toolkit/owt-client-native#300]
Hello guys,
I wanna compile for iOS SDK, so I followed the steps described in ReadME.md:
but getting the below error while trying to run this, `Build OWT iOS SDK with scripts\build.py`

> Traceback (most recent call last):
  File "./scripts/build.py", line 205, in <module>
    sys.exit(main())
  File "./scripts/build.py", line 199, in main
    if not runtest(opts.ssl_root):
  File "./scripts/build.py", line 157, in runtest
    getsdkversion(), '%s.app'%test_target],
  File "./scripts/build.py", line 145, in getsdkversion
    sdk_info.FillXcodeVersion(settings)
TypeError: FillXcodeVersion() missing 1 required positional argument: 'developer_dir'

I'm using Python3. Does anyone have any suggestions?
Thank you

**Comment by Ponsen** [comment]
Changing line 145 in build.py to the following fixed it for me:
`sdk_info.FillXcodeVersion(settings, None)`

**Comment by routsrv** [comment]
@Ponsen  Thanx for your suggestion. I tried this one but again m getting below error.

> Traceback (most recent call last):
  File "./scripts/build.py", line 205, in <module>
    sys.exit(main())
  File "./scripts/build.py", line 199, in main
    if not runtest(opts.ssl_root):
  File "./scripts/build.py", line 157, in runtest
    getsdkversion(), '%s.app'%test_target],
  File "./scripts/build.py", line 145, in getsdkversion
    sdk_info.FillXcodeVersion(settings, None)
  File "./build/config/mac/sdk_info.py", line 58, in FillXcodeVersion
    settings['xcode_version'] = FormatVersion(lines[0].split()[-1])
  File "./build/config/mac/sdk_info.py", line 42, in FormatVersion
    major, minor, patch = SplitVersion(version)
  File "./build/config/mac/sdk_info.py", line 29, in SplitVersion
    version = version.split('.')
TypeError: a bytes-like object is required, not 'str'

I run it with `python ./scripts/build.py` instead of `python3 ./scripts/build.py` and removed the test case, now it's working fine, but after that how to create a build in iOS??

**Comment by jianjunz** [comment]
Oh, we're still using Python 2.7. I think we should move to Python 3 as Python 2 is EOLed.

The binaries generated could be find in _out_ directory.

**Comment by jianjunz** [comment]
I think you are able to run the compile script with Python 2 now. A new issue #304 has been created to track the progress of moving all scripts and CI environment to Python 3.
