### ISSUE TITLE
WebRTC stack build dependencies.

### ISSUE THREAD

**Issue by yiyuan-liaoqiang** [open-webrtc-toolkit/owt-client-native#313]
'WebRTC stack build dependencies' cannot open.404

**Comment by jianjunz** [comment]
Thanks for reporting this issue. Please see [this page](https://webrtc.googlesource.com/src/+/refs/heads/master/docs/native-code/development/prerequisite-sw/index.md) instead. webrtc.org has been redesigned recently.

I'll submit a PR to fix this link.

**Comment by XueshiQiao** [comment]
link mentioned earlier is 404 too, this is latest one: [https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/development/prerequisite-sw/README.md](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/development/prerequisite-sw/README.md)
