### ISSUE TITLE
ffmpeg build error

### ISSUE THREAD

**Issue by anhminhdinh** [open-webrtc-toolkit/owt-client-native#329]
ERROR:
`../../third_party/ffmpeg/libavcodec/pcm.c(623): error C2059: syntax error: 'string'`

Build command:
`python build-win.py --gn_gen --sdk --scheme release --arch x86 --ssl_root c:\local\openssl_1.1.0l\x86\release  --msdk_root "C:\Program Files (x86)\IntelSWTools\Intel(R) Media SDK 2018 R1\Software Development Kit"  --output_path d:\dev\owt\x86\release`

Branch master, 3a705cf
Boost 1.67.0

**Comment by anhminhdinh** [comment]
For reference: 
Build for x64 are ok with debug/release
Build for x86 failed for both debug/release, same error

**Comment by taste1981** [comment]
which branch are you buding this on? make sure you run gclient sync before building so that patch at https://github.com/open-webrtc-toolkit/owt-client-native/blob/master/talk/owt/patches/0014-Fix-missing-ffmpeg-configure-item-for-msvc-build.patch is applied.

**Comment by minhdinh-luni** [comment]
> which branch are you buding this on? make sure you run gclient sync before building so that patch at https://github.com/open-webrtc-toolkit/owt-client-native/blob/master/talk/owt/patches/0014-Fix-missing-ffmpeg-configure-item-for-msvc-build.patch is applied.

As mentioned on bug description: 
> Branch master, [3a705cf](https://github.com/open-webrtc-toolkit/owt-client-native/commit/3a705cff8ca0046ff82d7de6189431bbd8ab31b3)

**Comment by taste1981** [comment]
As you see in above patch, we only make sure x64 build with MSVC. If you would like x86 to be enabled, you need to patch more files.

**Comment by anhminhdinh** [comment]
> As you see in above patch, we only make sure x64 build with MSVC. If you would like x86 to be enabled, you need to patch more files.

Hello, which file was it?

**Comment by taste1981** [comment]
third_party/ffmpeg/chromium/config/Chrome/win-msvc/ia32/config.h;
and also if neccessary, add change in third_party/ffmpeg/ffmpeg_generated.gni for what we've done for x64.

**Comment by anhminhdinh** [comment]
Hello,
It is working now.
What I did:
third_party/ffmpeg/chromium/config/Chrome/win-msvc/ia32/config.h:
Add at line 1055 
`#define CONFIG_PCM_VIDC_DECODER 0`
and at 1339
`#define CONFIG_PCM_VIDC_ENCODER 0`

For third_party/ffmpeg/ffmpeg_generated.gni
line 541 ->
`if (is_win && ((current_cpu == "x64") || (current_cpu == "x86"))) {`
