### ISSUE TITLE
Leave room callback not immediate

### ISSUE THREAD

**Issue by AshineReal** [open-webrtc-toolkit/owt-client-native#372]
Hi jianjunz, How to build sio lib with tls no verification ?

Otherwise , i find sio event delay so much, while switch network,or owt leave room.
for eg.
i trigger leave room like

```
  [self.owtConferenceClient leaveWithOnSuccess:^{
        CLogInfo(@"owt client leave room success.");
    } onFailure:^(NSError * _Nonnull error) {
        CLogInfo(@"owt client leave room failed");
    }];
```

it callback after about 3 seconds.

or switch from wifi -> 4g

socketio trigger reconnecting about 30+ seconds.

i suggest libsioclient_tls_no_verification.a in CS_WebRTC_Client_SDK_iOS.v4.3 is a debug version cause this.

can u give me some help ?

thank you jianjunz!

**Comment by jianjunz** [comment]
Hi,

Callback of leaving a conference is called when Socket.IO reports disconnect successfully. Perhaps you could debug the socket.io cpp library to see what happened.
