### ISSUE TITLE
Error in sdk ios? Need to reconnect between http and https?

### ISSUE THREAD

**Issue by PRIESt512** [open-webrtc-toolkit/owt-client-native#377]
Hello! I can not understand why in js there is a check for secure, but in the ios code there is no. -> Method - Join a conference.

JS:
`const isSecured = (token.secure === true);
if (host.indexOf('http') === -1) {
        host = isSecured ? ('https://' + host) : ('http://' + host);
      }
`

iOS:
`std::string scheme("http://");
  std::string host;
  rtc::GetStringFromJsonObject(json_token, "host", &host);
...
socket_client_->connect(scheme.append(host));
`

**Comment by jianjunz** [comment]
Duplicates #364.

**Comment by PRIESt512** [comment]
Thanks!!
