### ISSUE TITLE
How to get write access to the repository

### ISSUE THREAD

**Issue by PRIESt512** [open-webrtc-toolkit/owt-client-native#379]
I want to commit, create a separate branch, but I do not have write permissions...

**Comment by zhouhuirun2015** [comment]
1. fork.
2. edit the source file which you want to commit on original branch.
![image](https://user-images.githubusercontent.com/15274287/88653733-08237200-d0ff-11ea-8ea2-7f0ec5066208.png)
![image](https://user-images.githubusercontent.com/15274287/88654018-5fc1dd80-d0ff-11ea-8ea9-bd4679a670e8.png)
![image](https://user-images.githubusercontent.com/15274287/88654308-c810bf00-d0ff-11ea-946b-725077bd943d.png)

**Comment by taste1981** [comment]
Closing this issue as solved.
