### ISSUE TITLE
participantDidLeave cannot be called

### ISSUE THREAD

**Issue by yiyuan-liaoqiang** [open-webrtc-toolkit/owt-client-native#392]
iOS platform。when update to the latest version，this func cannot be called when other user leave the room
- (void)participantDidLeave:(OWTConferenceParticipant*)participant

**Comment by yiyuan-liaoqiang** [comment]
this commit leads to this problem #358。

**Comment by jianjunz** [comment]
Hi,

I'm not able to reproduce this issue with 358 applied. `participantDidLeave` was called as expected. If you still encounter this issue, please describe your steps to reproduce in detail. Thanks.
