### ISSUE TITLE
P2P Inter Platform connection Issue

### ISSUE THREAD

**Issue by Gokulakrishnan2788** [open-webrtc-toolkit/owt-client-native#399]
We are facing the issue when try to connect the Peer form one platform to another , for instance the peer from android can not get the video and audio from Web/iOS and vice versa.

We are allowing the peerId at run time up on receiving the incoming call request and publishing the audio/video/both the stream.  Also the track info and stream info are received across all platforms. 

Can any one help us at the earliest?

Thanks
Pramati Dev Team

**Comment by taste1981** [comment]
> We are facing the issue when try to connect the Peer form one platform to another , for instance the peer from android can not get the video and audio from Web/iOS and vice versa.
> 
> We are allowing the peerId at run time up on receiving the incoming call request and publishing the audio/video/both the stream. Also the track info and stream info are received across all platforms.
> 
> Can any one help us at the earliest?
> 
> Thanks
> Pramati Dev Team

Please specify the commit ID you're at. Codecs used on each platform,  test application you're using.

**Comment by taste1981** [comment]
@Gokulakrishnan2788, No further feedback, I'm closing this issue.
