### ISSUE TITLE
如何生成VS的工程？

### ISSUE THREAD

**Issue by syjml** [open-webrtc-toolkit/owt-client-native#401]
能否把项目构建成VS支持的项目？

**Comment by taste1981** [comment]
gn gen --ide=vs <your output dir> 
This will generate all.sln under your output dir (according to the gn args you specified before you run gn gen).
but this only generates a sln for viewing the code, or to attach to a process using the stack for debugging purpose, it's not targeted for building the entire stack.

**Comment by syjml** [comment]
> gn gen --ide = vs
> 这将在输出目录下生成all.sln（根据运行gn gen之前指定的gn args）。
> 但这只会生成一个用于查看代码的sln，或使用堆栈将其附加到进程中以进行调试的目的，而不是用于构建整个堆栈。

![QQ图片20200818162627](https://user-images.githubusercontent.com/8069021/90489276-a7241280-e16f-11ea-9845-8aeec773ece3.png)
报错了。。。

**Comment by taste1981** [comment]
the error message is clear enough, you are missing the output dir.
Not sure why github stripped some of my comment, but your command should be something like:

gn gen --ide=vs out/release-x64

**Comment by syjml** [comment]
> the error message is clear enough, you are missing the output dir.
> Not sure why github stripped some of my comment, but your command should be something like:
> 
> gn gen --ide=vs out/release-x64

![image](https://user-images.githubusercontent.com/8069021/90493170-988c2a00-e174-11ea-8a7b-987f7887cfd2.png)
还是继续报错。。。

**Comment by taste1981** [comment]
gn gen will try to find args.gn under out/release-x64 for your above sample. So before you run gn gen,  first make sure "gn args out/release-x64" succeed without any issue.

**Comment by syjml** [comment]
@taste1981 3Q，搞定了。
