### ISSUE TITLE
No stream when published with H265 on Android, with server H265 turned on

### ISSUE THREAD

**Issue by hzwzju** [open-webrtc-toolkit/owt-client-native#415]
Environment: Version 4.3
Issue: 
I have installed SVT-HEVC Encoder on the server.
I could subscribe H265 streams from the server if I published with H264/VP8/VP9 on Android.
But if i publish with H265, I couldn't subscribe a valid stream whatever the codec was.
Does server support H265 decoding?

**Comment by jianjunz** [comment]
Hi,

If you're asking about server capabilities, https://github.com/open-webrtc-toolkit/owt-server would be the repository for your question. Thanks.

**Comment by hzwzju** [comment]
> Hi,
> 
> If you're asking about server capabilities, https://github.com/open-webrtc-toolkit/owt-server would be the repository for your question. Thanks.

Hi.
I tested H265 encoding in P2P and there was a black screen but H264 was OK. Is it an issue abount Android client's H265 RTP packetizer? Tested with OPPO Reno Ace and MEIZU 16X.

**Comment by yiyuan-liaoqiang** [comment]
安卓265源码有问题，需要改源码

**Comment by hzwzju** [comment]
Problem solved. The latest SDK has solved the issue.
Like H264, VPS/SPS/PPS/SEI and I frame should be packed together in H265.
In owt-client-native\src\third_party\webrtc\sdk\android\src\java\org\webrtc\HardwareVideoEncoder.java or your own videoEncoder implementation.
In `deliverEncodedImage()`, insert configBuffer before codecOutputBuffer. It would look like
`        ByteBuffer frameBuffer;
        if (isKeyFrame && (codecType == VideoCodecType.H264 || codecType == VideoCodecType.H265)) {
            frameBuffer = ByteBuffer.allocateDirect(info.size + configBuffer.capacity());
            configBuffer.rewind();
            frameBuffer.put(configBuffer);
            frameBuffer.put(codecOutputBuffer);
            frameBuffer.rewind();
        } else {
            frameBuffer = codecOutputBuffer.slice();
        }`
