### ISSUE TITLE
Failed to set local SDP

### ISSUE THREAD

**Issue by syjml** [open-webrtc-toolkit/owt-client-native#422]
After the owt Windows client establishes a p2p connection with the web client, the Windows client will report an error when publishing the video stream, and the content is: Failed to set local SDP.

The Windows client and the web client are in the same LAN.
[log.txt](https://github.com/open-webrtc-toolkit/owt-client-native/files/5290895/log.txt)

**Comment by syjml** [comment]
@jianjunz  @taste1981

**Comment by syjml** [comment]
I found that when using VP8 or VP9 encoding, the web client can receive the video stream.

**Comment by taste1981** [comment]
No activities for over 1 year. Closing this issue.
