### ISSUE TITLE
error LNK2005

### ISSUE THREAD

**Issue by syjml** [open-webrtc-toolkit/owt-client-native#431]
In the master branch, owt integrates the ffmpeg library, and my own programs also need to rely on the ffmpeg library. When I use the ffmpeg library integrated by owt, the avcodec_find_encoder_by_name method will return empty, and the avcodec_find_encoder method will also return empty. Since owt integrates ffmpeg, it conflicts with my own ffmpeg library. What should I do?

![image](https://user-images.githubusercontent.com/8069021/98318408-85715380-2019-11eb-8ca4-2fec7b36d061.png)

**Comment by taste1981** [comment]
you can avoid defining ffmpeg_branding and also set rtc_use_h264 to false. Closing this issue as it was non active for over 6 months.
