### ISSUE TITLE
Android Upate to 83 will lead publish video stream not work

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-native#435]
1: android join mcu server
2: android publish local stream to mcu 

except:
    publish success ,and other client can subscribe android remote stream

actual:
   publish trigger success callback , but oher client can not trigger onStreamAdd event, and android client sendBitrate = 0 

android devices: xiaomi 8
mcu version 20201118-ubuntu.tar.gz
android native: 83
android sdk: master

**Comment by zhangyihui1** [comment]
verify ok

**Comment by herryfan** [comment]
on huawei p30, native master+webrtc 83-sdk, same issue with h264 hardware encoder
