### ISSUE TITLE
No 10.12+ SDK found

### ISSUE THREAD

**Issue by krishnastvSMSC** [open-webrtc-toolkit/owt-client-native#439]
Hello Team,

My Mac system OS Version : 10.15.7 (Catalina)
                     Xcode  Version : 12.2
When I run the python script with python 2, got error 

<img width="820" alt="Screenshot 2020-11-23 at 6 36 00 PM" src="https://user-images.githubusercontent.com/45424351/99965335-bcd25500-2dba-11eb-8f44-7cbd2865abd5.png">

when I run the python script with python 3.8.3, got another error

<img width="819" alt="Screenshot 2020-11-23 at 6 37 02 PM" src="https://user-images.githubusercontent.com/45424351/99965439-e1c6c800-2dba-11eb-80b1-ea2d778a83bf.png">

Can any one help me to resolve these issues.

Thank you in advance.

**Comment by krishnastvSMSC** [comment]
Hello Team,

Any one refer solution for my above issue.

Thank you

**Comment by jianjunz** [comment]
Hi,

This issue will be fixed by #436.

**Comment by krishnastvSMSC** [comment]
Hi Team,

When I Clone from git, didn't fine these merges in the scripts..

<img width="931" alt="Screenshot 2020-11-25 at 8 17 32 AM" src="https://user-images.githubusercontent.com/45424351/100176624-ad582680-2ef6-11eb-937e-ca676a83ecb3.png">

From where I can download updated source..

Thank you

**Comment by jianjunz** [comment]
Closing this issue since #436 is merged.
