### ISSUE TITLE
windows p2p test Connect to Incorrect Server return not false

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-client-native#441]
********* Start testing of CTestSdk *********
Config: Using QtTest library 5.11.1, Qt 5.11.1 (x86_64-little_endian-llp64 shared (dynamic) release build; by MSVC 2015)
INFO   : CTestSdk::initTestCase() entering
PASS   : CTestSdk::initTestCase()
INFO   : CTestSdk::testConnect_toIncorrectServer_shouldFail() entering
FAIL!  : CTestSdk::testConnect_toIncorrectServer_shouldFail() 'm_testClient1->Connect(localUser, WRONG_SERVER_ADDRESS, false)' returned FALSE. ()
d:\mingkai\cppcheckin\owtchat\owtchat\testconnect.cpp(47) : failure location
INFO   : CTestSdk::cleanupTestCase() entering
PASS   : CTestSdk::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 26037m

**Comment by taste1981** [comment]
This is not caused by SDK. it's issue in the signaling channel implementation. A sample implementation for you to enable this:
    std::map<std::string, std::string> query;
    sio::socket::ptr socket = io_->socket();
    io_->set_reconnect_attempts(2);      // Add this line.
    io_->set_reconnect_delay(2000);     // Add this line.
    std::string owt_chat = "owt-message";
    std::string auth_msg_type = "authentication";
    sio::message::ptr jsonObject = sio::object_message::create();
    jsonObject->get_map()["token"] = sio::string_message::create(token);

    io_->set_open_listener([=] {
        io_->socket()->emit(auth_msg_type, jsonObject, [=](const sio::message::list& msg) {
            if (msg.size() > 0 && msg[0]->get_flag() == sio::message::flag_integer) {
                int64_t error_code = msg[0]->get_int();
                if (on_failure) {
                    std::unique_ptr<Exception> exception(
                        new Exception(ExceptionType::kP2PConnectionAuthFailed,
                            "Authentication failed."));
                    on_failure(std::move(exception));
                }
                return;
            }
            std::string uid = msg[0]->get_map()["uid"]->get_string().data();
            if (connect_success_callback_) {
                connect_success_callback_(uid);
            }
            });
        });
   // ***************Add below code****************
    io_->set_fail_listener([=] {
        if (on_failure) {
            std::unique_ptr<Exception> exception(
                new Exception(ExceptionType::kP2PUnknown,
                    "Server connection failed."));
            on_failure(std::move(exception));
          }
        });

**Comment by GaoMingKai** [comment]
automation will fix
