### ISSUE TITLE
windows p2p test Connect to CorrectServer Then Disconnect Then not return

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-client-native#442]
********* Start testing of CTestSdk *********
Config: Using QtTest library 5.11.1, Qt 5.11.1 (x86_64-little_endian-llp64 shared (dynamic) release build; by MSVC 2015)
INFO   : CTestSdk::initTestCase() entering
PASS   : CTestSdk::initTestCase()
INFO   : CTestSdk::testConnect_toCorrectServerThenDisconnectThenConnect_shouldSucceed() entering
FAIL!  : CTestSdk::testConnect_toCorrectServerThenDisconnectThenConnect_shouldSucceed() 'm_testClient1->Disconnect(true)' returned FALSE. ()

**Comment by taste1981** [comment]
This is not caused by SDK. you will need to modify your signaling channel implementation, the ::Disconnect API, after io_->close(), add following code:
    if (on_success) {
        on_success();
    }
With this you should get the disconnect success callback invoked.

**Comment by GaoMingKai** [comment]
automation will fix
