### ISSUE TITLE
Participant Left

### ISSUE THREAD

**Issue by krishnastvSMSC** [open-webrtc-toolkit/owt-client-native#45]
Hello,

How we can know if any participant is left from conference. As we check with Android Framework for every participant, have observer to check the state when left the room.

For iOS framework ICSConferenceParticipant Class doesn't contains any Delegate to know.

We check ICSRemoteStreamDelegate method streamDidEnd  but its not accurate, sometimes getting 2 participant records even though only one participant in conference.

How we can achieve "If any participant left the room".

 

Thanks 

Krishna

**Comment by jianjunz** [comment]
Thanks for requesting this feature. It will be added in future releases.
