### ISSUE TITLE
Installing the conference test app will produce an error on iPhone 7 plush

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-client-native#467]
Details

Unable to install "ICS Conference"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103

Could not inspect the application package.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTRadarComponentKey = 282703;
    MobileDeviceErrorCode = "(0xE8000051)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012775cc8f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000012779b241 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010997564b DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000012779af82 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000012760ba10 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000109aa417e __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000109aa5da0 __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff2018d5dd _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff2018e7c7 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff201945fe _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff201950cb _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff2019ec5d _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff20336499 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff20335467 start_wqthread + 15
);
}

System Information

macOS Version 11.0.1 (Build 20B50)
Xcode 12.3 (17715) (Build 12C33)
Timestamp: 2021-01-04T09:22:15+08:00

**Comment by jianjunz** [comment]
It's more like to be a deployment problem, rather than something can be fixed in SDK.

**Comment by GaoMingKai** [comment]
After I reset the environment, pod installs the new worksapce, but the app installation is still the same error.

**Comment by GaoMingKai** [comment]
I changed to a new environment and the test app can be installed normally.
