### ISSUE TITLE
v5.0-rc.c Build Windows failed!!

### ISSUE THREAD

**Issue by liubin123456** [open-webrtc-toolkit/owt-client-native#485]
C:\code\owt5.0\src>python scripts\build-win.py --arch=x64 --scheme=release --gn_gen --sdk --ssl_root "C:\OpenSSL-Win64"  --msdk_root "C:\Program Files (x86)\IntelSWTools\Intel(R) Media SDK 2019 R1\Software Development Kit"  --output_path "C:\code\owt5.0\src\out\owt-x64-build"
Namespace(arch='x64', docs=False, gn_gen=True, msdk_root='C:\\Program Files (x86)\\IntelSWTools\\Intel(R) Media SDK 2019 R1\\Software Development Kit', output_path='C:\\code\\owt5.0\\src\\out\\owt-x64-build', scheme='release', sdk=True, ssl_root='C:\\OpenSSL-Win64', tests=False)
ERROR at //third_party/webrtc/BUILD.gn:432:12: Unsupported value in libs.
  libs = [ "Foundation.framework" ]
           ^---------------------
Use frameworks to list framework dependencies.
See //talk/owt/BUILD.gn:58:7: which caused the file to be included.
      "//third_party/webrtc",

**Comment by taste1981** [comment]
Please use v5.0 tag instead of any Rc tags. I'm deleting those tags. Closing this issue.
