### ISSUE TITLE
socket.io ping timeout

### ISSUE THREAD

**Issue by ettwz** [open-webrtc-toolkit/owt-client-native#494]
Hello,

I'm using client-native for windows. 
There is a problem that socketIO connection will break after 90 seconds.

log of portal:

> 2021-03-03 09:21:33.323  - DEBUG: SocketIOServer - notify participant: VVZ1kRnztRPnncrJAAAr event: participant data: { action: 'join',
> 2021-03-03 09:21:33.323  - DEBUG: SocketIOServer - sendMessage, event: participant data: { action: 'join',
> 2021-03-03 09:21:33.325  - DEBUG: SocketIOServer - onClientJoined, id: vnx9CAKLjI-q_pVpAAAt client.tokenCode: 28009351042
> 2021-03-03 09:21:33.700  - DEBUG: SocketIOServer - notify participant: vnx9CAKLjI-q_pVpAAAt event: progress data: { id: 'a9327643b51946479bf07beaaf65495b',
> 2021-03-03 09:21:33.700  - DEBUG: SocketIOServer - sendMessage, event: progress data: { id: 'a9327643b51946479bf07beaaf65495b',
> 2021-03-03 09:21:33.751  - DEBUG: SocketIOServer - notify participant: vnx9CAKLjI-q_pVpAAAt event: progress data: { id: 'a9327643b51946479bf07beaaf65495b', status: 'ready' }
> 2021-03-03 09:21:33.751  - DEBUG: SocketIOServer - sendMessage, event: progress data: { id: 'a9327643b51946479bf07beaaf65495b', status: 'ready' }
> 2021-03-03 09:21:33.752  - DEBUG: SocketIOServer - notify participant: vnx9CAKLjI-q_pVpAAAt event: progress data: { id: 'a9327643b51946479bf07beaaf65495b',
> 2021-03-03 09:21:33.752  - DEBUG: SocketIOServer - sendMessage, event: session-progress data: { id: 'a9327643b51946479bf07beaaf65495b',
> 2021-03-03 09:22:03.744  - DEBUG: SocketIOServer - **_socket.io disconnected, reason: ping timeout_**
> 2021-03-03 09:23:03.745  - INFO: SocketIOServer - **_vnx9CAKLjI-q_pVpAAAt waiting for reconnecting timeout._**
> 2021-03-03 09:23:03.745  - DEBUG: SocketIOServer - forceClientLeave, client_id: vnx9CAKLjI-q_pVpAAAt
> 2021-03-03 09:23:03.746  - DEBUG: SocketIOServer - onClientLeft, id: vnx9CAKLjI-q_pVpAAAt
> 2021-03-03 09:23:03.774  - DEBUG: SocketIOServer - notify participant: VVZ1kRnztRPnncrJAAAr event: participant data: { action: 'leave', data: 'vnx9CAKLjI-q_pVpAAAt' }
> 2021-03-03 09:23:03.774  - DEBUG: SocketIOServer - sendMessage, event: participant data: { action: 'leave', data: 'vnx9CAKLjI-q_pVpAAAt' }

version:
owt-client-native: `4.3.1`
owt-server: `efbee445e0f4f9bdb28daae2759f24c9efd7ab05`

I'm not sure the root cause is client-native or socketIO.
client-android and client-javascript is everything ok.

**Comment by ryan255** [comment]
same problem

**Comment by tischd** [comment]
Same problem here. Have you ever found a workaround?
This way the C++ client is simply unusable.

**Comment by ettwz** [comment]
> Same problem here. Have you ever found a workaround?
> This way the C++ client is simply unusable.
#
I change the version of socker.io on owt-client-native-4.3.1. It work well now.

FYI: [Update commit hash for Socket.IO cpp. (#519)](https://github.com/open-webrtc-toolkit/owt-client-native/commit/2dd5e6ab26aced450494198df6b378edaa1abccc)
