### ISSUE TITLE
ninja sub command failed for last build_linux.py file

### ISSUE THREAD

**Issue by Prudhvi1357** [open-webrtc-toolkit/owt-client-native#505]
Dear Team,

Getting below error for last command "python build_linux.py --gn_gen --sdk --tests --ssl_root ~/cert/" where cert is empty director.

                 from ../../third_party/webrtc/test/time_controller/external_time_controller.cc:10:
/usr/include/c++/5/bits/stl_pair.h:112:26: note: candidate: constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = webrtc::Module* const; _T2 = std::unique_ptr<webrtc::ExternalTimeController::ProcessThreadWrapper::ModuleWrapper>]
       _GLIBCXX_CONSTEXPR pair(const _T1& __a, const _T2& __b)
                          ^
/usr/include/c++/5/bits/stl_pair.h:112:26: note:   no known conversion for argument 2 from 'webrtc::ExternalTimeController::ProcessThreadWrapper::ModuleWrapper*' to 'const std::unique_ptr<webrtc::ExternalTimeController::ProcessThreadWrapper::ModuleWrapper>&'
/usr/include/c++/5/bits/stl_pair.h:108:26: note: candidate: constexpr std::pair<_T1, _T2>::pair() [with _T1 = webrtc::Module* const; _T2 = std::unique_ptr<webrtc::ExternalTimeController::ProcessThreadWrapper::ModuleWrapper>]
       _GLIBCXX_CONSTEXPR pair()
                          ^
/usr/include/c++/5/bits/stl_pair.h:108:26: note:   candidate expects 0 arguments, 2 provided
cc1plus: warning: unrecognized command line option '-Wno-class-memaccess'
cc1plus: warning: unrecognized command line option '-Wno-packed-not-aligned'
[1804/3769] CXX obj/third_party/webrtc/modules/congestion_controller/goog_cc/probe_controller/probe_controller.o
ninja: build stopped: subcommand failed.

**Comment by taste1981** [comment]
Please provide more details on the build host. (Linux distribution version & gcc/g++ version), and branch/commit id that shows this error.

**Comment by Prudhvi1357** [comment]
Hi

Linux= ubuntu16.04 gcc=7.5v branch: 5.0.x

**Comment by taste1981** [comment]
Please check with "python build_linux.py --gn_gen --sdk ---scheme release --arch x64" when calling the build script. As the first  step please do not specify --ssl_root or --tests

**Comment by Alex-YddeR** [comment]
can we build IOS binary release in Linux OS

**Comment by taste1981** [comment]
No we don't support build iOS in Linux. Closing this issue if no further question.
