### ISSUE TITLE
Windows/iOS p2p client cannot send message each other successfully

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#51]

**Comment by JinChengShi** [comment]
1. windows client1 login and add allowed to client2
2. windows client2 login and add allowed to client1
3. windows client1 send to client2

in step 3 client1 cannot send message to client2 successfully

**Comment by taste1981** [comment]
should have been fixed by PR70.

**Comment by JinChengShi** [comment]
This issue verified with latest stack is OK.
