### ISSUE TITLE
windows conference publish H264 codec stream success,but it will frozen in mix stream

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#52]
1. windows conference client login 
2. windows conference client publish camera stream with H264 codec
3. windows conference client subscribe mix stream

expected: the stream publish by windows client should be will in mix stream
actually: the stream publish by windows client is frozen in mix stream

**Comment by JinChengShi** [comment]
encoded h264 stream is ok in this case

**Comment by taste1981** [comment]
This should have been fixed by PR70.

**Comment by JinChengShi** [comment]
This issue verified with the latest stack is OK.
