### ISSUE TITLE
windows conference cannot publish H265 codec stream

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#53]
1. windows conference client login
2. windows conference client publish camera stream with H265 codec
3. windows conference client subscribe mix stream

expected: the stream publish by windows client should be will in mix stream
actually: the stream publish by windows client cannot display in mix stream

**Comment by taste1981** [comment]
Known issue on some hosts. Might only work on x64 build with GACC plugin.

**Comment by JinChengShi** [comment]
This issue has been fixed in x64 build, but x86 build still not work.

**Comment by taste1981** [comment]
windows SDK now switch to GACC hevc encoder plugin which is only supported on x64 build.
