### ISSUE TITLE
windows cannot subscribe the forward or stream with other codec after subscribe it with h265 codec failed

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#55]
windows hardware is closed:
1. windows client login and publish a stream to mcu
2. windows client subscribe mix or forward with h265 codec 
3. windows client subscribe mix or forward with other codec

in step 2, it will return "subscribe failed:Fail to set local description.!" msg from callback
in step 3, it will return "stream has already been subscribed. Subcribe after it is unsubscribed!" msg from callback

**Comment by taste1981** [comment]
Should have been fixed by PR70.

**Comment by JinChengShi** [comment]
This issue is OK with the latest stack.
