### ISSUE TITLE
ios conference published stream video will frozen when locked screen 

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#56]
1. ios client login and publish a stream to mcu
2. other client subscribe the forward stream published by ios client
3. ios locked the screen
4. ios unlocked the screen

expected: after step 3, the video should display normally in other client
actually: after step 3, the video will be frozen

**Comment by jianjunz** [comment]
This is expected. Camera doesn't send frames to inactive apps.
