### ISSUE TITLE
Build dynamic library for linux

### ISSUE THREAD

**Issue by RayanWang** [open-webrtc-toolkit/owt-client-native#571]
Hello, can I build the SDK to a dynamic library? If so, how to do this?
Thanks in advance.

**Comment by ysc3839** [comment]
No. Component builds are not supported in WebRTC.
https://webrtc.googlesource.com/src/+/954f7274ac91594d0e06ec052d0d0401631d02ee/webrtc.gni#27

**Comment by RayanWang** [comment]
OK. Thank you for your reply.
