### ISSUE TITLE
Does  owt-client-native support Linux?

### ISSUE THREAD

**Issue by superHHD** [open-webrtc-toolkit/owt-client-native#597]
Does the  owt-client-native support running on Linux(ubuntu18.04)？From the documents generated by Doxygen, I only see that windows can be supported, not Linux

**Comment by jianjunz** [comment]
It's expected to work, but no bot is monitoring its status. Thus, changes break Linux build may not be detected and finally got merged. Free feel to report any issues for Linux build.

**Comment by superHHD** [comment]
I see. Thank you
