### ISSUE TITLE
"local encoded stream" has not been implemented yet?

### ISSUE THREAD

**Issue by hxl-dy** [open-webrtc-toolkit/owt-client-native#64]
https://github.com/open-webrtc-toolkit/owt-client-native/blob/04e4961c45967abeb2df3d8025b9a0b1b6e68bef/talk/owt/sdk/include/cpp/owt/base/localcamerastreamparameters.h#L78

in windows sdk sample(.\CS_WebRTC_Client_SDK_Windows.v4.1.1\samples\ConfSampleMFC\ConfSampleMFC):
![image](https://user-images.githubusercontent.com/15082228/54810952-57af8d80-4cc2-11e9-8ec7-185d439f2898.png)

**Comment by taste1981** [comment]
It's implemented. The sample just shows one of the case that stream input comes for encoded file.
