### ISSUE TITLE
build error  ios

### ISSUE THREAD

**Issue by LaoWangInNear** [open-webrtc-toolkit/owt-client-native#742]
vpython scripts/build.py --sio_root /usr/local/ --skip_tests --scheme release
ERROR at //build/config/compiler/BUILD.gn:1343:22: Script returned non-zero exit code.
    clang_revision = exec_script("//tools/clang/scripts/update.py",
                     ^----------
Current dir: /Users/wangjinchao/webrtc_h265/src/out/Release-device-arm64/
Command: python3 /Users/wangjinchao/webrtc_h265/src/tools/clang/scripts/update.py --print-revision --verify-version=18
Returned 1 and printed out:

The expected clang version is llvmorg-18-init-12938-geb1d5065-1 but the actual version is llvmorg-16-init-6578-g0d30e92f-1
Did you run "gclient sync"?

who can help me

**Comment by LaoWangInNear** [comment]
ok

**Comment by zainanjum100** [comment]
i am facing the same issue any solution?

**Comment by panjekm** [comment]
@LaoWangInNear Im also facing this issue, how did you resolve it?
