### ISSUE TITLE
windows p2p client will be crashed when publish to js client in debug mode

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#77]
OWTChat.exe!issue_debug_notification(const wchar_t * const message) Line 28	C++
 	OWTChat.exe!__acrt_report_runtime_error(const wchar_t * message) Line 154	C++
 	OWTChat.exe!abort() Line 51	C++
 	[External Code]	
 	[Inline Frame] OWTChat.exe!rtc::webrtc_checks_impl::LogStreamer<>::Call(const char * file, const int line, const char * message) Line 198	C++
 	[Inline Frame] OWTChat.exe!rtc::webrtc_checks_impl::FatalLogCall<0>::operator&(const rtc::webrtc_checks_impl::LogStreamer<> & streamer) Line 272	C++
 	OWTChat.exe!cricket::UsedIds<cricket::Codec>::FindUnusedId() Line 372	C++
>	OWTChat.exe!cricket::UsedIds<cricket::Codec>::FindAndSetIdUsed(cricket::Codec * idstruct) Line 355	C++
 	OWTChat.exe!cricket::MergeCodecs<cricket::DataCodec>(const std::vector<cricket::DataCodec,std::allocator<cricket::DataCodec> > & reference_codecs, std::vector<cricket::DataCodec,std::allocator<cricket::DataCodec> > * offered_codecs, cricket::UsedPayloadTypes * used_pltypes) Line 858	C++
 	OWTChat.exe!cricket::MediaSessionDescriptionFactory::GetCodecsForOffer(const cricket::SessionDescription * current_description, std::vector<cricket::AudioCodec,std::allocator<cricket::AudioCodec> > * audio_codecs, std::vector<cricket::VideoCodec,std::allocator<cricket::VideoCodec> > * video_codecs, std::vector<cricket::DataCodec,std::allocator<cricket::DataCodec> > * data_codecs) Line 1632	C++
 	OWTChat.exe!cricket::MediaSessionDescriptionFactory::CreateOffer(const cricket::MediaSessionOptions & session_options, const cricket::SessionDescription * current_description) Line 1275	C++
 	OWTChat.exe!webrtc::WebRtcSessionDescriptionFactory::InternalCreateOffer(webrtc::CreateSessionDescriptionRequest request) Line 332	C++
 	OWTChat.exe!webrtc::WebRtcSessionDescriptionFactory::CreateOffer(webrtc::CreateSessionDescriptionObserver * observer, const webrtc::PeerConnectionInterface::RTCOfferAnswerOptions & options, const cricket::MediaSessionOptions & session_options) Line 234	C++
 	OWTChat.exe!webrtc::PeerConnection::CreateOffer(webrtc::CreateSessionDescriptionObserver * observer, const webrtc::PeerConnectionInterface::RTCOfferAnswerOptions & options) Line 1731	C++
 	OWTChat.exe!webrtc::ReturnType<void>::Invoke<webrtc::PeerConnectionInterface,void (webrtc::PeerConnectionInterface::*)(webrtc::CreateSessionDescriptionObserver *, const webrtc::PeerConnectionInterface::RTCOfferAnswerOptions &) __attribute__((thiscall)),webrtc::CreateSessionDescriptionObserver *,webrtc::PeerConnectionInterface::RTCOfferAnswerOptions>(webrtc::PeerConnectionInterface * c, void(webrtc::PeerConnectionInterface::*)(webrtc::CreateSessionDescriptionObserver *, const webrtc::PeerConnectionInterface::RTCOfferAnswerOptions &) m, webrtc::CreateSessionDescriptionObserver * a1, webrtc::PeerConnectionInterface::RTCOfferAnswerOptions a2) Line 123	C++
 	OWTChat.exe!webrtc::MethodCall2<webrtc::PeerConnectionInterface,void,webrtc::CreateSessionDescriptionObserver *,const webrtc::PeerConnectionInterface::RTCOfferAnswerOptions &>::OnMessage(rtc::Message *) Line 244	C++
 	OWTChat.exe!webrtc::internal::SynchronousMethodCall::OnMessage(rtc::Message *) Line 33	C++
 	OWTChat.exe!rtc::MessageQueue::Dispatch(rtc::Message * pmsg) Line 530	C++
 	OWTChat.exe!rtc::Thread::ProcessMessages(int cmsLoop) Line 499	C++
 	OWTChat.exe!rtc::Thread::Run() Line 328	C++
 	OWTChat.exe!rtc::Thread::PreRun(void * pv) Line 317	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]

**Comment by HuaChunbo** [comment]
The root cause is that doubled-addtrack in new stack will re-trigger offer creation which causes the reserved codec id from 96 to 127 used up, then RTC_DCHECK pops.
