### ISSUE TITLE
windows p2p client publish will crash after send message to windows client

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#86]
1. client1 login and add allowed
2. client2 login and add allowed
3. client1 send message to client2
4. client1 publish to client2

In step 4, windows client1 will be crash

**Comment by JinChengShi** [comment]
` 	OWTChat.exe!issue_debug_notification(const wchar_t * const message) Line 28	C++
 	OWTChat.exe!__acrt_report_runtime_error(const wchar_t * message) Line 154	C++
 	OWTChat.exe!abort() Line 51	C++
 	[External Code]	
>	[Inline Frame] OWTChat.exe!rtc::webrtc_checks_impl::LogStreamer<>::Call(const char * file, const int line, const char * message) Line 198	C++
 	[Inline Frame] OWTChat.exe!rtc::webrtc_checks_impl::FatalLogCall<0>::operator&(const rtc::webrtc_checks_impl::LogStreamer<> & streamer) Line 272	C++
 	OWTChat.exe!owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface> stream) Line 639	C++
 	OWTChat.exe!webrtc::PeerConnection::ApplyRemoteDescription(std::unique_ptr<webrtc::SessionDescriptionInterface,std::default_delete<webrtc::SessionDescriptionInterface> > desc) Line 2421	C++
 	OWTChat.exe!webrtc::PeerConnection::SetRemoteDescription(std::unique_ptr<webrtc::SessionDescriptionInterface,std::default_delete<webrtc::SessionDescriptionInterface> > desc, rtc::scoped_refptr<webrtc::SetRemoteDescriptionObserverInterface> observer) Line 2170	C++
 	OWTChat.exe!webrtc::PeerConnection::SetRemoteDescription(webrtc::SetSessionDescriptionObserver * observer, webrtc::SessionDescriptionInterface * desc) Line 2119	C++
 	OWTChat.exe!webrtc::ReturnType<void>::Invoke<webrtc::PeerConnectionInterface,void (webrtc::PeerConnectionInterface::*)(webrtc::SetSessionDescriptionObserver *, webrtc::SessionDescriptionInterface *) __attribute__((thiscall)),webrtc::SetSessionDescriptionObserver *,webrtc::SessionDescriptionInterface *>(webrtc::PeerConnectionInterface * c, void(webrtc::PeerConnectionInterface::*)(webrtc::SetSessionDescriptionObserver *, webrtc::SessionDescriptionInterface *) m, webrtc::SetSessionDescriptionObserver * a1, webrtc::SessionDescriptionInterface * a2) Line 123	C++
 	OWTChat.exe!webrtc::MethodCall2<webrtc::PeerConnectionInterface,void,webrtc::SetSessionDescriptionObserver *,webrtc::SessionDescriptionInterface *>::OnMessage(rtc::Message *) Line 244	C++
 	OWTChat.exe!webrtc::internal::SynchronousMethodCall::OnMessage(rtc::Message *) Line 33	C++
 	OWTChat.exe!rtc::MessageQueue::Dispatch(rtc::Message * pmsg) Line 530	C++
 	OWTChat.exe!rtc::Thread::ProcessMessages(int cmsLoop) Line 499	C++
 	OWTChat.exe!rtc::Thread::Run() Line 328	C++
 	OWTChat.exe!rtc::Thread::PreRun(void * pv) Line 317	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
`

**Comment by HuaChunbo** [comment]
Work fine when publishing after messaging first. Please use the latest stack.

**Comment by JinChengShi** [comment]
The latest stack works fine for this issue.
